import {Cart} from '@/actions/add-to-cart'
import {CartItem} from '@/components/cart-item'
import {Button} from '@/components/ui/button'
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet'
import {kv} from '@vercel/kv'
import {ShoppingBag} from 'lucide-react'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {cookies} from 'next/headers'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cartId = cookies().get('cartId')?.value
  const cart: Cart = (cartId ? await kv.get(cartId) : null) ?? {beers: []}
  return (
    <html lang="en">
      <header className="flex justify-between items-center p-4 h-16">
        <Sheet>
          <SheetTrigger asChild>
            <Button size="icon" className="relative" variant="outline">
              <ShoppingBag />
              {cart.beers.length > 0 ? (
                <div className="absolute -top-2 -right-2 bg-primary text-primary-foreground rounded-lg">
                  {cart.beers.length}
                </div>
              ) : null}
            </Button>
          </SheetTrigger>
          <SheetContent>
            <SheetHeader>
              <SheetTitle>Cart</SheetTitle>
              <SheetDescription>Shopping Cart</SheetDescription>
            </SheetHeader>
            <ul>
              {cart.beers.map(beer => (
                <CartItem key={beer.id} beer={beer} />
              ))}
            </ul>
          </SheetContent>
        </Sheet>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
