import {Cart} from '@/actions/add-to-cart'
import {CartSheet} from '@/components/cart-sheet'
import {kv} from '@vercel/kv'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {cookies} from 'next/headers'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cartId = cookies().get('cartId')?.value
  const cart: Cart = (cartId ? await kv.get(cartId) : null) ?? {beers: []}
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between items-center p-4 h-16 border-b border-border sticky top-0">
          <h1 className="text-2xl font-bold">Beer Store</h1>
          <CartSheet cart={cart} />
        </header>
        {children}
      </body>
    </html>
  )
}
